version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - "./db_data:/data/db"
    labels:
      - "traefik.enable=false"
  api:
    image: node
    volumes:
      - ".:/usr/src/app"
    ports:
      - 8888:8888
      - 1935:1935
    working_dir: /usr/src/app
    command: npm run server-watch
    labels:
      - "traefik.api2.weight=3"
      - "traefik.api2.port=8888"
      - "traefik.api2.frontend.rule=PathPrefixStrip:/api/media;AddPrefix:/api"
      - "traefik.api1.weight=2"
      - "traefik.api1.port=3000"
      - "traefik.api1.frontend.rule=PathPrefix:/api"
  web:
    image: node
    volumes:
      - ".:/usr/src/app"
    ports:
      - 1235:1235
    working_dir: /usr/src/app
    command: npm run start-docker
    labels:
      - "traefik.port=1234"
      - "traefik.weight=1"
      - "traefik.frontend.rule=PathPrefix:/"
  traefik:
    image: traefik
    restart: unless-stopped
    command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    ports:
      - 8000:80
      - 8001:8080
