version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - "./db_data:/data/db"
    labels:
      - "traefik.enable=false"
  api:
    image: tedkulp/node-ffmpeg:latest
    volumes:
      - ".:/usr/src/app"
      - "../Node-Media-Server:/usr/src/app/node_modules/node-media-server"
    ports:
      - 8888:8888
      # - 1935:1935
    working_dir: /usr/src/app
    command: npm run server-watch
    labels:
      - "traefik.http.routers.api1.entrypoints=http, traefik"
      - "traefik.http.routers.api1.service=api1"
      - "traefik.http.routers.api1.priority=2"
      - "traefik.http.routers.api1.rule=PathPrefix(`/api`)||PathPrefix(`/socket.io`)||PathPrefix(`/thumbnails`)"
      - "traefik.http.services.api1.loadbalancer.server.port=3000"
      - "traefik.http.routers.api2.entrypoints=http, traefik"
      - "traefik.http.routers.api2.service=api2"
      - "traefik.http.routers.api2.priority=3"
      - "traefik.http.routers.api2.rule=PathPrefix(`/live`)"
      - "traefik.http.services.api2.loadbalancer.server.port=8888"
      - "traefik.tcp.routers.rtmp.entrypoints=rtmp"
      - "traefik.tcp.routers.rtmp.service=rtmp"
      - "traefik.tcp.routers.rtmp.rule=HostSNI(`*`)"
      - "traefik.tcp.services.rtmp.loadbalancer.server.port=1935"
  web:
    image: node
    volumes:
      - ".:/usr/src/app"
      - "../Node-Media-Server:/usr/src/app/node_modules/node-media-server"
    ports:
      - 1235:1235
    working_dir: /usr/src/app
    command: npm run start-docker
    labels:
      - "traefik.http.routers.web.entrypoints=http, traefik"
      - "traefik.http.routers.web.priority=1"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=1234"
  traefik:
    image: traefik
    restart: unless-stopped
    command: --api.insecure=true --providers.docker --entryPoints.rtmp.address=:1935 --entryPoints.http.address=:80
    # command: --api.insecure=true --providers.docker
    # command: --api --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    ports:
      - 8000:80
      - 8001:8080
      - 1935:1935
